<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../KuizServer/Hubs/GameHub.cs" Link="GameHub.cs" />
    <Compile Include="../../KuizServer/Services/LobbyService.cs" Link="LobbyService.cs" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.2" />
  </ItemGroup>
</Project>
